version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - "9411:9411"
    networks:
      - erudio-network
  springcloud-configserver:
    image: leandrocgsi/springcloud-configserver:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
    networks:
      - erudio-network
  naming-server:
    image: leandrocgsi/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - erudio-network
  api-gateway:
    image: leandrocgsi/api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411/
    networks:
      - erudio-network
  cambio-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3308"
    networks:
      - erudio-network
  book-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3310:3310"
    networks:
      - erudio-network
  cambio-service:
    image: leandrocgsi/cambio-service
    restart: always
    build:
      context: .
      dockerfile: 08-cambio-service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
      - cambio-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123
    networks:
      - erudio-network
  book-service:
    image: leandrocgsi/book-service
    restart: always
    build:
      context: .
      dockerfile: 08-book-service/Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - book-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: admin123
    networks:
      - erudio-network
networks:
    erudio-network:
        driver: bridge
    